seajs.config({
  comboSyntax: ['combo/', ','],
  base: window.baseUrl  + '/js/',
  alias: {
	    "jquery": "jquery/jquery-1.10.2.js",
	    "jquery.cookie": "jquery/jquery.cookie.js",
	    "jquery.ui.core": "jquery/ui/jquery.ui.core.js",
	    "jquery.ui.draggable": "jquery/ui/jquery.ui.draggable.js",
	    "jquery.ui.droppable": "jquery/ui/jquery.ui.droppable.js",
	    "jquery.ui.mouse": "jquery/ui/jquery.ui.mouse.js",
	    "jquery.ui.position": "jquery/ui/jquery.ui.position.js",
	    "jquery.ui.resizable": "jquery/ui/jquery.ui.resizable.js",
	    "jquery.ui.widget": "jquery/ui/jquery.ui.widget.js",
	    "jquery.ui.menu": "jquery/ui/jquery.ui.menu.js",
	    "jquery.ui.tooltip": "jquery/ui/jquery.ui.tooltip.js",
	    "jquery.ui.autocomplete": "jquery/ui/jquery.ui.autocomplete.js",
	    "jquery.ui.button": "jquery/ui/jquery.ui.button.js",
	    "jquery.ui.dialog": "jquery/ui/jquery.ui.dialog.js",
	    "jquery.fileupload":"jquery/fileupload/jquery.fileupload.js",
	    "jquery.fileupload-image":"jquery/fileupload/jquery.fileupload-image.js",
	    "jquery.fileupload-process":"jquery/fileupload/jquery.fileupload-process.js",
	    "jquery.fileupload-validate":"jquery/fileupload/jquery.fileupload-validate.js",
	    "jquery.fileupload-voide":"jquery/fileupload/jquery.fileupload-voide.js",
	    "jquery.fileupload-transport":"jquery/fileupload/jquery.iframe-transport.js",
	    "jquery.load-image":"jquery/load-image/load-image.js",
	    "jquery.load-image-exif":"jquery/load-image/load-image-exif.js",
	    "jquery.load-image-exif-map":"jquery/load-image/load-image-exif-map.js",
	    "jquery.load-image-ios":"jquery/load-image/load-image-ios.js",
	    "jquery.load-image-meta":"jquery/load-image/load-image-meta.js",
	    "jquery.load-image-orientation":"jquery/load-image/load-image-orientation.js",
	    "jquery.canvas-to-blob":"jquery/canvas-to-blob.js",
	    "jquery.photobooth":"jquery/jquery.photobooth.js",
	    "jquery.scriptcam":"jquery/jquery.scriptcam.js",
	    "jquery.smartWizard":'jquery/jquery.smartWizard-2.0.js',
	    "jquery.foxibox":"jquery/jquery-foxibox-0.2.js",
	    "jquery.printarea":"jquery/jquery.printarea.js",
	    "jquery.jqprint":"jquery/jquery.jqprint.js",
	    "jquery.ztree":"jquery/jquery.ztree.all-3.5.js",
	    "jquery.ztree.exhide":"jquery/jquery.ztree.exhide-3.5.js",
	    "jquery.resizableColumns": "jquery/jquery.resizableColumns.js",
	    "jquery.nicescroll": "jquery/jquery.nicescroll.js",
	    "jquery.blockUI": "jquery/jquery.blockUI.min.js",
	    "jquery.mousewheel":"jquery/jquery.mousewheel.js",
	    
	    "fileinput":"jquery/fileupload/fileinput.js",
	    
	    "knockout":"jquery/knockout-3.2.0.js",
	    
	    "bootstrap":"bootstrap/v2/bootstrap.js",
	    "bootstrap3":"bootstrap/bootstrap.js",
	    "bootstrap.datepicker":"bootstrap/bootstrap-datepicker.js",
	    "bootstrap.datetimepicker":"bootstrap/bootstrap-datetimepicker-new.js",
	    "bootstrap.multiselect":"bootstrap/bootstrap-multiselect.js",
	    "bootstrap.select":"bootstrap/bootstrap-select.js",
	    
	    "umeditor.config":"umeditor/umeditor.config.js",
	    "umeditor.lang":"umeditor/lang/zh-cn/zh-cn.js",
	    "umeditor":"umeditor/umeditor.js",
	    "summernote":"jquery/summernote/summernote.js",
	    
	    "myui.pager":'myui/ui.bootstrap.pager.js',
	    "myui.datatable":'myui/ui.bootstrap.datatable.js',
	    "myui.webform":'myui/jquery.webform.js',
	    "myui.alert":"myui/jquery.alert.js",
	    
	    "myutil.rest":"utils/jquery.rest.js",
	    "myutil.init":"utils/auto-init.js",
	    "myutil.common":"utils/common.js",
	    
	    "swf.swfobject":"utils/swfobject.js",
	    
	    "custom.idcard":"custom/idcard.js",
	    "custom.fingerPrint":"custom/fingerPrint.js",
	    "custom.combobox":"custom/combobox.js",
	    
	    "select2":"custom/select2.js",
	    "gpsdate":"op/jquery.gpsdate.js",
	    "BMap_plugin":"op/BMap.plugin.js",
	    "slider":"jquery/ui/jquery.ui.slider.js",
	    "rotate":"jquery/jquery.rotate.js",
	    
	    "highcharts":"highchart/highcharts.js",
	  "statcharts": 'dqa/statcharts.js',
	    "select3":"myui/jquery.select3.js",
	    "exporting":"highchart/modules/exporting.js",
	    "jquery.multi-select":"jquery/jquery.multi-select.js"
  }
});