//element, event, module, target, operator, useCapture
seajs.use(['jquery'], function($) {
	$(function() {
		Analysis.config([
		    /* 全局按钮或工具 */
			['#btn-save', 'click', '全局', '保存'],
			['#btn-draft', 'click', '全局', '草稿'],
			['#viewReverse', 'click', '全局', '查看反向', undefined, true],
			['#mouse_distance', 'click', '工具', '测距'],
			['#view_change', 'click', '工具', '视图切换'],
			['#lengend_img', 'click', '工具', '图例'],
			/* tab */
			['#myTab a[href="#line"]', 'click', '线路', '线路tab'],
			['#myTab a[href="#trajectory"]', 'click', '脊线', '脊线tab'],
			['#myTab a[href="#stops"]', 'click', '站点', '站点推荐tab'],
			['#myTab a[href="#more"]', 'click', '更多', '更多tab'],
			/* 线路 */
			['#line_reset_btn', 'click', '线路', '还原', '线路信息'],
			['#select2-crossCity-container', 'click', '线路', '跨城线路', '线路信息'],
			['#lineExtendAccordion', 'click', '线路', '线路扩展信息', '线路信息'],
			/* 站点 */
			['#stop_reset_btn', 'click', '站点', '还原', '站点列表'],
			['#table-map-body tr', 'click', '站点', '点击', '站点列表'],
			['#table-map-body tr', 'dblclick', '站点', '双击', '站点列表'],
			['#table-map-body tr .add', 'click', '站点', '新增', '站点列表'],
			['#table-map-body tr .modify', 'click', '站点', '修改', '站点列表'],
			['#table-map-body tr .delete', 'click', '站点', '删除', '站点列表'],
			['#table-map-body tr .history', 'click', '站点', '历史', '站点列表'],
			/* 逻辑站左键 */
			['#lgorang_station', 'click', '站点', '显示附近物理站', '逻辑站', true],
			['#lgorang_station_hidden3', 'click', '站点', '隐藏附近物理站', '逻辑站', true],
			['#ycstation', 'click', '站点', '隐藏站点', '逻辑站'],
			['#merge_ycstation', 'click', '站点', '合并物理站', '逻辑站'],
			['#lgostation_merge', 'click', '站点', '合并逻辑站到物理站', '逻辑站', true],
			['#rangMarker_save', 'click', '站点', '保存附近物理站地铁信息', '逻辑站', true],
			/* 虚拟物理站左键 */
			['#vri_changeto_rel', 'click', '站点', '转真实物理站', '虚拟物理站', true],
			['#vri_phystation_split', 'click', '站点', '拆分', '虚拟物理站', true],
			['#vri_hide_station', 'click', '站点', '隐藏逻辑站', '虚拟物理站', true],
			['#vri_table_close', 'click', '站点', '关闭', '虚拟物理站', true],
			/* 真实物理站左键 */
			['#rel_phystation_split', 'click', '站点', '拆分', '真实物理站', true],
			['#showrangestation', 'click', '站点', '显示附近物理站', '真实物理站', true],
			['#lgorang_station_hidden2', 'click', '站点', '隐藏物理站', '真实物理站', true],
			['#ycstation', 'click', '站点', '隐藏站点', '真实物理站'],
			['#merge_ycstation', 'click', '站点', '合并物理站', '真实物理站'],
			/* 逻辑站或虚拟物理站或真实物理站右键 */
			['#btn_save1', 'click', '站点', '修改', '逻辑站', true],
			['#btn_save2', 'click', '站点', '修改', '虚拟物理站', true],
			['#btn_save3', 'click', '站点', '修改', '真实物理站', true],
			['#btn_remove1', 'click', '站点', '删除', '逻辑站', true],
			['#btn_remove2', 'click', '站点', '删除', '虚拟物理站', true],
			['#btn_remove3', 'click', '站点', '删除', '真实物理站', true],
			/* 双击新增站点 */
			['#btn_insert', 'click', '站点', '新增', '逻辑站', true],
			['#btn_remove_1', 'click', '站点', '新增删除', '逻辑站', true],
			['#lgorang_station_hidden1', 'click', '站点', '隐藏周围物理站', '逻辑站', true],
			/* 脊线 */
			['#trajectory .cll-btn-query', 'click', '脊线', '查询', '车辆GPS'],
			['#trajectory .change-cars', 'click', '脊线', '换一批', '车辆GPS'],
			['#trajectory .uncheck-cars', 'click', '脊线', '隐藏', '车辆GPS'],
			['#trajectory #nodirection', 'click', '脊线', '双向GPS', '车辆GPS'],
			['#trajectory .datepicker', 'click', '脊线', '日期', '车辆GPS'],
			['#trajectory #tra_reset_btn', 'click', '脊线', '还原', '脊线圈列表'],
			['#jx-tbody .delete', 'click', '脊线', '删除', '脊线圈列表'],
			['#jx-tbody tr', 'click', '脊线', '点击', '脊线圈列表'],
			['#jx-tbody tr', 'dblclick', '脊线', '双击', '脊线圈列表'],
			['#jx-batch-del', 'click', '脊线', '批量删除', '脊线圈列表'],
			['#btn_remove4', 'click', '脊线', '删除', '脊线圈', true],
			/* 站点推荐tab */
			['#stop-query', 'click', '站点', '同名站点-显示', '站点推荐'],
			['#clear_samestop', 'click', '站点', '同名站点-隐藏', '站点推荐'],
			['#btn-choose1', 'click', '站点', '同名站点-选择', '站点推荐', true],
			['#heatmap_btn', 'click', '站点', '热力图-显示', '站点推荐'],
			['#clear_heatmap_btn', 'click', '站点', '热力图-隐藏', '站点推荐'],
			['#heatmap_date', 'click', '站点', '热力图-日期', '站点推荐'],
			['#lines_heatmap', 'click', '站点', '热力图-同名站点', '站点推荐'],
			['.BMapLib_rectangle', 'click', '站点', '热力图-矩形', '站点推荐', true],
			['#user-query', 'click', '站点', '用户位置-显示', '站点推荐'],
			['#clear-uq', 'click', '站点', '用户位置-隐藏', '站点推荐'],
			['#collec-show', 'click', '站点', '采集站点-显示', '站点推荐'],
			['#collec-hide', 'click', '站点', '采集站点-隐藏', '站点推荐'],
			['.seeImg', 'click', '站点', '采集站点-查看图片', '站点推荐'],
			['#app-stop-query', 'click', '站点', '站点GPS-显示', '站点推荐'],
			['#app-stop-clear', 'click', '站点', '站点GPS-隐藏', '站点推荐'],
			['#appupdstop', 'click', '站点', '站点GPS-更新', '站点推荐'],
			['#avg-speed', 'click', '站点', '低速区-显示', '站点推荐'],
			['#clear-speed', 'click', '站点', '低速区-隐藏', '站点推荐'],
			['#a_stop_btn', 'click', '站点', '高德站点-显示', '站点推荐'],
			['#cancel_a_stop_btn', 'click', '站点', '高德站点-隐藏', '站点推荐'],
			['#showGaoDeAll', 'click', '站点', '高德站点-显示全部站点', '站点推荐'],
			['#hideGaoDeAll', 'click', '站点', '高德站点-隐藏全部站点', '站点推荐'],
			['#a-result a.shadow', 'click', '站点', '高德站点-投影', '站点推荐'],
			['#updstop', 'click', '站点', '高德站点-替换', '站点推荐', true],
			['#recommand_stop_btn', 'click', '站点', '百度站点-显示', '站点推荐'],
			['#cancel_recommand_stop_btn', 'click', '站点', '百度站点-隐藏', '站点推荐'],
			['#his-query', 'click', '站点', '站点历史-显示', '站点推荐'],
			['#clear_history', 'click', '站点', '站点历史-隐藏', '站点推荐'],
			['#pickup', 'click', '站点', '附近站点-拾取', '站点推荐'],
			['#show-pickup-point', 'click', '站点', '附近站点-显示', '站点推荐'],
			['#clear-pickup-point', 'click', '站点', '附近站点-隐藏', '站点推荐'],
			['#btn-choose2', 'click', '站点', '附近站点-选择', '站点推荐', true],
			['#show-point', 'click', '站点', '坐标查询工具-显示', '站点推荐'],
			['#clear-point', 'click', '站点', '坐标查询工具-隐藏', '站点推荐'],
			['#show-lnglat-convert', 'click', '站点', '经纬度转换工具-显示', '站点推荐'],
			['#clear-lnglat-convert', 'click', '站点', '经纬度转换工具-隐藏', '站点推荐'],
			/* 更多tab */
			['#line-reverse-gen', 'click', '线路', '反向生成线路', '更多'],
			['#jx-reverse', 'click', '脊线', '脊线反序', '更多'],
			['#jx-exchange', 'click', '脊线', '脊线换向', '更多'],
			['#jx-compress', 'click', '脊线', '脊线压缩', '更多']
		]);
	});
});